site_name: mkcloud
#theme: readthedocs
repo_url: https://github.com/kormay/
edit_uri: ""
repo_name: GitHub

pages:
  - 介绍: index.md
  - 工具:
      - Anaconda: tools/anaconda.md
  - MySql:
      - 引擎: mysql/engine.md
      - 索引: mysql/indexing.md
      - Mysql查询优化示例: mysql/examples.md
  - 操作系统:
      - 进程线程和协程: os/ProcessThreadCoroutine.md
