site_name: mkcloud
#theme: readthedocs
repo_url: https://github.com/kormay/
edit_uri: ""
repo_name: GitHub

pages:
  - Introduction: index.md
  - Tools:
      - Anaconda: tools/anaconda.md
  - MySql:
      - Engine: mysql/engine.md
      - Indexing: mysql/indexing.md
      - Mysql查询优化示例: mysql/examples.md
  - OS:
      - Process and Thread and Coroutine: os/ProcessThreadCoroutine.md
